Add new tests for dataset collection and new functionality
cqfn/veniq pull request #34
Opened 2020-10-06 09:50 UTC by lyriccoder

Add new tests for dataset collection and new functionality for types identification

2020-10-06 14:56 UTC, acheshkov requested changes
Please remove function comments and improve variable and method names to improve understandability

2020-10-06 14:56 UTC, acheshkov commented on veniq/dataset_collection/augmentation.py
>      :return: int - type
It has another return type

2020-10-06 14:56 UTC, acheshkov commented on veniq/dataset_collection/augmentation.py
> +def determine_type(
please come up better method name

2020-10-06 14:56 UTC, acheshkov commented on veniq/dataset_collection/types_identifier.py
> +class AlgorithmFactory(metaclass=Singleton):
why we need Factory pattern here?

2020-10-06 21:05 UTC, Vitaly-Protasov commented
@acheshkov  I agree that its must to add better names for functions. But with functionality I am defenityle agree

2020-10-06 21:06 UTC, Vitaly-Protasov approved these changes

2020-10-07 11:24 UTC, aravij requested changes
There is some code to simplify.
Also take a look at `builder` pattern, you might need it in you further work with factory.

2020-10-07 11:24 UTC, aravij commented on veniq/dataset_collection/augmentation.py
> +    Run function to check whether Method declaration can be inlined
Does this function checks if the method has return type or is it can be inlined?

2020-10-07 11:24 UTC, aravij commented on veniq/dataset_collection/augmentation.py
> +    for x in method_decl.get_proxy_nodes(ASTNodeType.VARIABLE_DECLARATOR):
`VARIABLE_DECLARATION` and `LOCAL_VARIABLE_DECLARATION` does not have `name` field. They have array `declarators`. Each `VARIABLE_DECLARATOR` has `name` field. `VARIABLE_DECLARATION` and `LOCAL_VARIABLE_DECLARATION` has field `names` to get array of `name` of each `declorator`.

I think now you can avoid `hasattr` function.

2020-10-07 11:24 UTC, aravij commented on veniq/dataset_collection/augmentation.py
> +            else:
A lot of else statements. Kind of difficult to read. Can you refactor it a bit with less indentation depth.

2020-10-08 07:09 UTC, closed without merging