SEMI baseline: grouping based on size
cqfn/veniq pull request #4
Opened 2020-09-21 13:39 UTC by KatGarmash

implements one of the grouping criterion for extract opportunities: similar size (line 7, Fig. 7 from the paper)

2020-09-21 14:26 UTC, lyriccoder commented
I would add License info. Should we do it? @acheshkov

2020-09-21 15:45 UTC, acheshkov commented
@lyriccoder we have MIT license already

2020-09-22 06:55 UTC, acheshkov requested changes

2020-09-22 06:55 UTC, acheshkov commented on test/baselines/semi/test_grouping_size.py
> +                         False)
Here are two different tests.

2020-09-22 08:08 UTC, acheshkov commented on veniq/baselines/semi/grouping_size.py
> +    """
```suggestion
def is_similar_size(
    range_1: Tuple[int, int],
    range_2: Tuple[int, int],
    max_size_difference: float = 0.2
) -> bool:
    """

```

2020-09-22 08:17 UTC, acheshkov commented on test/baselines/semi/test_grouping_size.py
> +                         False)
split on two tests

2020-09-22 08:39 UTC, KatGarmash commented on test/baselines/semi/test_grouping_size.py
> +                         False)
fixed

2020-09-22 08:39 UTC, acheshkov approved these changes

2020-09-22 08:51 UTC, merged